.\"
.\" Copyright (c) 2010 Dru Lavigne <dru@freebsd.org>
.\"
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"
.Dd September 4, 2014
.Dt WEBCAMD 8 
.Os FreeBSD
.Sh NAME
.Nm webcamd
.Nd daemon to provide access to USB webcam and DVB devices
.Sh SYNOPSIS
.Nm
.Op Fl B
.Op Fl D Ar <host:port:ndev>
.Op Fl L Ar <host:port:ndev>
.Op Fl U Ar <user>
.Op Fl G Ar <group>
.Op Fl H
.Op Fl M Ar <matchindex>
.Op Fl N Ar <devicename>
.Op Fl S Ar <deviceserialnumber>
.Op Fl d Ar [ugen]<unit>.<addr>
.Op Fl i Ar <interface or client number>
.Op Fl v Ar <video device number>
.Op Fl m Ar <parameter>=<value>
.Op Fl r
.Op Fl l
.Op Fl s
.Op Fl h
.Sh DESCRIPTION
.Nm
is a daemon that enables the use of hundreds of different USB
webcam and DVB devices under the FreeBSD operating
system. The webcam daemon is basically a port
of Linux USB device drivers into userspace on FreeBSD. 
.Pp
.Nm 
requires the 
.Xr cuse4bsd 3 
kernel module. To load the driver as a
module at boot time, place the following line in
.Xr loader.conf 5 :
.Pp
       cuse4bsd_load="YES"
.Pp
To start 
.Nm
automatically at system startup, place the following line in
.Xr rc.conf 5 :
.Pp
	webcamd_enable="YES"
.Pp
Once
.Nm
is running, supported USB web cameras and DVB devices will be available for use by other applications.
.Pp
The following options are available:
.Bl -tag -width indent
.It Fl B
Run the daemon in background mode.
.It Fl d
Specify the <unit>.<addr> of the USB device to use.
This option can be combined with -N and -S options.
.It Fl f
If the device requires a firmware file, specify the path to the firmware.
The default firmware path is /boot/modules.
.It Fl h
Print help text showing available options.
.It Fl m
Specify the value of a parameter.
Note that escaping is not supported for strings.
.It Fl i
Specify the interface number to use.
.It Fl r
Do not set realtime priority.
.It Fl S
Attach to device matching the given serial number.
This option can be combined with -d and -N options.
.It Fl M
Specify the match index when using -S and -N options.
This option is useful when multiple USB devices share the same serial
and devicename to be able to distinguish them.
Default is zero.
.It Fl N
Attach to device matching the given device name.
This option can be combined with -d and -S options.
.It Fl l
List the available USB devices and the needed command line for binding
to the given device.
.It Fl s
Show available parameters.
.It Fl v
Specify the video device number.
.It Fl U
Set the user identification for all character devices created by webcamd.
Default value: webcamd
.It Fl G
Set the group identification for all character devices created by webcamd.
Default value: webcamd
.It Fl H
Register device by the HAL daemon.
.It Fl D
Enable vTuner client support.
Connect to one or more remote DVB device instead of using USB.
The vTuner protocol needs eight ports for normal operation which are allocated back to back.
One port for control communication and the other port for data communication.
NOTE: If you want to start multiple vTuner clients in the background by use of the
.Fl B
option, you need to supply a unique interface number for each client using th
.Fl i
option.
.It Fl L
Enable vTuner server support.
Make the DVB device available on TCP/IP instead of Cuse4BSD.
If the ndev parameter is negative, all present DVB devices
are mapped to TCP/IP.
Else only the given number of DVB devices are mapped.
The vTuner protocol needs eight ports for normal operation which are allocated back to back.
One port for control communication and the other port for data communication.
.El
.Sh EXAMPLES
With the USB device connected, determine the [ugen]<unit>.<addr> values using 
.Xr usbconfig 8 :
.Pp
.Bd -literal -offset indent
usbconfig
ugen7.2: <product 0x0991 vendor 0x046d> at usbus7, cfg=0 md=HOST spd=HIGH (480Mbps) pwr=ON
.Ed
.Pp
Create a vTuner client:
.Bd -literal -offset indent
webcamd -D 127.0.0.1:5100:1:2
.Ed
.Pp
Create a vTuner server:
.Bd -literal -offset indent
webcamd -L 127.0.0.1:5100:-1
.Ed
.PP
.Sh NOTES
All character devices are created using the 0660 mode which gives the user and group read and write permissions.
.Sh FILES
.Bl -tag -compact
.It Pa /usr/local/etc/devd/webcamd.conf
.It Pa /usr/local/etc/rc.d/webcamd
.It Pa /var/run/webcamd.*.0.pid
.Sh SEE ALSO
.Xr a800 4 ,
.Xr af9005 4 ,
.Xr af9015 4 ,
.Xr anysee 4 ,
.Xr au0828 4 ,
.Xr au6610 4 ,
.Xr b2c2 4 ,
.Xr benq 4 ,
.Xr ce6230 4 ,
.Xr cinergy 4 ,
.Xr conex 4 ,
.Xr cpiax 4 ,
.Xr cxusb 4 ,
.Xr dib0700 4 ,
.Xr digitv 4 ,
.Xr dtt200u 4 ,
.Xr dtv5100 4 ,
.Xr dw2102 4 ,
.Xr ec168 4 ,
.Xr em28xx 4 ,
.Xr et61x251 4 ,
.Xr finepix 4 ,
.Xr friio 4 ,
.Xr gl860 4 ,
.Xr gl861 4 ,
.Xr gp8psk 4 ,
.Xr hdpvr 4 ,
.Xr ibmcam 4 ,
.Xr jeilinj 4 ,
.Xr m5602 4 ,
.Xr m920x 4 ,
.Xr mars 4 ,
.Xr mr800 4 ,
.Xr mr97310a 4 ,
.Xr nova-t 4 ,
.Xr opera1 4 ,
.Xr ov519 4 ,
.Xr ov534 4 ,
.Xr pacxxx 4 ,
.Xr pvrusb2 4 ,
.Xr pwc 4 ,
.Xr s2255 4 ,
.Xr se401 4 ,
.Xr siano 4 ,
.Xr sn9c102 4 ,
.Xr sn9c20x 4 ,
.Xr sonixj 4 ,
.Xr spca5xx 4 ,
.Xr sq905c 4 ,
.Xr stk014 4 ,
.Xr stv06xx 4 ,
.Xr sunplus 4 ,
.Xr t613 4 ,
.Xr ttusb2 4 ,
.Xr tv8532 4 ,
.Xr umt 4 ,
.Xr usbvision 4 ,
.Xr uvc 4 ,
.Xr vc032x 4 ,
.Xr vp702x 4 ,
.Xr vp7045 4 ,
.Xr zc3xx 4 ,
.Xr zr364xx 4 
.Sh AUTHORS
.Nm
was written by
.An Hans Petter Selasky hselasky@freebsd.org . This man page was written by
Dru Lavigne dru@freebsd.org.
.Pp
