#
# Makefile for Webcamd
#
obj-y += linux_defs.o
obj-y += linux_file.o
obj-y += linux_firmware.o
obj-y += linux_func.o
obj-y += linux_i2c.o
obj-y += linux_i2c_mux.o
obj-y += linux_mod_param.o
obj-y += linux_section.o
obj-y += linux_struct.o
obj-y += linux_task.o
obj-y += linux_thread.o
obj-y += linux_timer.o
obj-y += linux_usb.o

obj-$(CONFIG_WEBCAMD_HAL) += linux_hal.o
