.\"
.\" Copyright (c) 2010 Dru Lavigne <dru@freebsd.org>
.\"
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL 
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"
.Dd Nov 30, 2010
.Dt BTTV 4
.Os FreeBSD
.Sh NAME
.Nm bttv
.Nd bttv webcamd driver for TV cards
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
The
.Nm
driver supports TV cards based on the BT848 and BT878 chipsets. 
.Pp
Devices using the
.Nm
driver become available to other applications once
.Xr webcamd 8
is loaded.
.Sh HARDWARE
The
.Nm
driver should work with the following TV cards. The
.Xr pciconfig 8
command can be used to determine the VendorID:ProductID of the device.
.Pp
.Bl -column -compact ".Li 0fe9:d62" "DViCO FusionHDTV USB"
.It Em "VendorID:ProductID" Ta Em Device
.It 0000:a155	 Ta "IVC-200"
.It 0000:f050	 Ta "IVCE-8784"
.It 0001:a155	
.It 0001:f050	
.It 0002:a155	
.It 0002:f050	
.It 0003:a155	
.It 0003:f050	
.It 0070:13eb	 Ta "Hauppauge ImpactVCB (bt878)"
.It 0070:3900	 Ta "Hauppauge"
.It 0070:4500	 Ta "Hauppauge WinTV PVR"
.It 0070:ff00	 Ta "Osprey 100/150 (878)"
.It 0070:ff01	 Ta "Osprey 200/201/250/251"
.It 0070:ff02	 Ta "Osprey 500"
.It 0070:ff03	 Ta "Osprey 2000"
.It 0070:ff04	 Ta "Osprey 540"
.It 0070:ff07	 Ta "Osprey 440"
.It 0071:0101	 Ta "Nebula Electronics DigiTV"
.It 008a:763c	 Ta "Geovision GV-600"
.It 0100:a155	
.It 0101:a155	
.It 0102:a155	
.It 0103:a155	
.It 0304:0102	 Ta "Grand X-Guard"
.It 036e:109e	 Ta "Conceptronic CTVFMi v2"
.It 0800:a155	
.It 0801:a155	
.It 0802:a155	
.It 0803:a155	
.It 0a01:17de	 Ta "Jetway TV/Capture JW-TV878-FBK"
.It 0e11:0079	 Ta "Canopus WinDVR PCI"
.It 1000:1801	 Ta "Encore ENL TV-FM-2"
.It 1002:0001	 Ta "ATI TV-Wonder"
.It 1002:0003	 Ta "ATI TV-Wonder VE"
.It 107d:6606	 Ta "Leadtek WinFast 2000"
.It 107d:6607	 Ta "Winfast VC100"
.It 107d:6609	 Ta "Leadtek WinFast 2000 XP"                   
.It 10b4:2636	 Ta "STB TV PCI FM"
.It 10b4:2637	 Ta "3Dfx VoodooTV FM (Euro)"
.It 10b4:2645	 Ta "Gateway P/N 6000704 (bt878)"
.It 10fc:4020	 Ta "IODATA GV-BCTV3/PCI"
.It 10fc:4050	 Ta "IODATA GV-BCTV4/PCI"
.It 10fc:4070	 Ta "IODATA GV-BCTV5/PCI"
.It 10fc:d018	
.It 11bd:0012	 Ta "Pinnacle PCTV Studio/Rave/Pro"
.It 11bd:001c	 Ta "Pinnacle PCTV Sat"
.It 11bd:0026	 Ta "Twinhan DST"
.It 11bd:ff12	
.It 121a:3000	 Ta "VoodooTV 200"
.It 121a:3060	 Ta "3Dfx VoodooTV 100"
.It 1295:200a	 Ta "Imagenation PXC200"
.It 144f:3000	 Ta "Askey CPH06X TView99"
.It 144f:3002	 Ta "Askey CPH05X/06X"
.It 144f:3005	
.It 144f:5000	
.It 144f:a005	
.It 1461:0001	 Ta "AverMedia TVPhone 98"
.It 1461:0002	 Ta "AverMedia TVCapture 98"
.It 1461:0003	
.It 1461:0004	 Ta "AverMedia TVCapture 98"
.It 1461:0300	 Ta "AverMedia TVCapture 98"
.It 1461:0761	 Ta "AverMedia AverTV DVB-T 761"
.It 1461:0771	 Ta "AverMedia AVerTV DVB-T 771"
.It 14c7:0101	 Ta "Modular Technology MM201/MM202/MM205/MM210/MM215 PCT"
.It 153b:1117	 Ta "Terratec TValue"
.It 153b:1118	
.It 153b:1119	
.It 153b:111a	
.It 153b:1123	 Ta "Terratec TV/Radio+"
.It 153b:1127	 Ta "Terratec TerraTV+ 1.0/1.1"
.It 153b:1134	
.It 153b:1135	 Ta "Terratec TValueRadio"
.It 153b:5018	
.It 153b:ff3b	
.It 1554:4011	 Ta "Prolink Pixelview PlayTV Pro rev.9B"
.It 15b0:4000	 Ta "Zoltrix Genie TV/FM"
.It 15b0:400a	
.It 15b0:400d	
.It 15b0:4010	
.It 15b0:4016	
.It 15cb:0101	 Ta "AG Electronics GMV1"
.It 1805:0105	 Ta "Euresys Picolo Tetra"
.It 1805:0106	
.It 1805:0107	
.It 1805:0108	
.It 1822:0001	
.It 1822:0026	
.It 1830:1540	 Ta "ProVideo PV183"
.It 1831:1540	
.It 1832:1540	
.It 1833:1540	
.It 1834:1540	
.It 1835:1540	
.It 1836:1540	
.It 1837:1540	
.It 1851:1850	 Ta "Lifeview FlyVideo 98 LR50"
.It 1851:1851	 Ta "Lifeview FlyVideo 98EZ LR51"
.It 1851:a050	 Ta "Chronos Video Shuttle II"
.It 1852:1852	 Ta "Lifeview FlyVideo 98FM LR50"
.It 1852:1852	 Ta "Terratec TerraTV+ Version 1.1 (bt878)"
.It 1f7f:1850	 Ta "Lifeview FlyVideo 98 LR50"
.It 2636:10b4	 Ta "Hauppauge"
.It 270f:fc00	
.It 4149:5353	 Ta "SSAI Security/Ultrasound Video"
.It 4344:4142	 Ta "GrandTec Grand Video Capture (Bt848)"
.It 6000:0311	 Ta "Sensoray 311"
.It 6606:217d	
.It 7063:2000	 Ta "pcHDTV HD-2000 TV"
.It 800a:763d	 Ta "Geovision GV-800(S)"
.It 800c:763d	
.It 800d:763d	
.It 9511:1540	 Ta "Acorp Y878F"
.It a04f:a0fc	
.It a051:41a0	 Ta "Lifeview FlyVideo 98FM LR50"
.It a1a0:a0fc	 Ta "Zoltrix TV-Max"
.It aa00:1430	 Ta "ProVideo PV143"
.It aa00:1431	
.It aa00:1432	
.It aa00:1433	
.It aa00:1460	 Ta "ProVideo PV150" 
.It aa01:1461	
.It aa02:1462	
.It aa03:1433	
.It aa03:1463	
.It aa04:1464	
.It aa05:1465	
.It aa06:1466	
.It aa07:1467	
.It aa0c:146c	 Ta "ProVideo PV951"
.It aa6a:82b2	 Ta "SIMUS GVC1100"
.It bd11:1200	
.It bd11:ff00	
.It dbc0:d200	 Ta "DViCO FusionHDTV 2"
.It f6ff:fff6	
.It ff00:a132	 Ta "IVC-100" 
.It ff00:a182	 Ta "IVC-120G"
.It ff01:a182	
.It ff02:a182	
.It ff03:a182	
.It ff04:a182	
.It ff05:a182	
.It ff06:a182	
.It ff07:a182	
.It ff08:a182	
.It ff09:a182	
.It ff0a:a182	
.It ff0b:a182	
.It ff0c:a182	
.It ff0d:a182	
.It ff0e:a182	
.It ff0f:a182	
.It 	 Ta AD-TVK503
.It		  Ta Adlink RTV24
.It		  Ta ADS Technologies Channel Surfer TV
.It		  	Aimslab Video Highway Xtreme (VHX)
.It		  	APAC Viewcomp 878(AMAX)
.It	  		Askey CPH03x
.It 	 Ta Asound Skyeye PCTV
.It 	 Ta AVEC Intercapture
.It		 	BESTBUY Easy TV
.It	 		CEI Raffles Card
.It 	 Ta Diamond DTV2000
.It	 	 	DSP Design TCVIDEO
.It	 	 	Dynalink Magic TView
.It 	 Ta Eagle Wireless Capricorn2 (bt878A)
.It	 	 	Formac iProTV
.It	 	 	Formac ProTV I/II 
.It 	 Ta GrandTec Multi Capture Card (Bt878)
.It	 	 	Hercules Smart TV Stereo
.It	 	 	IDS Eagle
.It	 	 	IMS/IXmicro TurboTV
.It	 	 	Intel Create and Share PCI
.It	 	 	Intel Smart Video Recorder III
.It	 	 	InterVision IV-560
.It	 	 	Kodicom 4400R
.It	 	 	Kozumi KTV-01C
.It	 	 	Kworld KW-TV878RF
.It	 	 	Leadtek WinView 601
.It	 	 	Lenco MXTV-9578 CP
.It		 	Lifetec LT 9415 TV [LR90]
.It	 		Lifeview FlyKit LR38
.It	 		Lifeview FlyVideo 2000/2000S LR90
.It	 		Lifeview FlyVideo A2
.It	 		Lifeview FlyVideo II EZ/LR26 
.It	 		Little OnAir TV
.It	 		LMLBT4
.It	 		Lucky Star Image World ConferenceTV LR50
.It	 		MachTV
.It	 		MagicTV
.It	 	 	MATRIX Vision Sigma-SLC
.It	 	 	MATRIX Vision Sigma-SQ
.It	 	 	MATRIX-Vision MV-Delta/2
.It	 	 	MAXI TV Video PCI2 LR26/LR50
.It	  		MIRO PCTV/Pro
.It	  		Modular Technology MM100PCTV
.It	  		NGS NGSTV+
.It 	  		Osprey 101/151/210/220/230
.It	  		Pace TV & Radio Card
.It	  		Phoebe Tv Master/FM
.It	  		PHYTEC VD-009 Combi/MiniDIN)
.It	  		PHYTEC VD-009-X1 VD-011 Combi/MiniDIN
.It	  		PHYTEC VD-012 X1/X2
.It	  		PixelView PlayTV PAK 
.It	  		Powercolor MTV878/MTV878R/MTV878F
.It	  		Prolink PixelView PlayTV MPEG2 PV-M4900
.It	  		Prolink PixelView PlayTV pro
.It	  		Prolink Pixelview PV-BT878P+ (Rev.2E, 4C, 4E, or 8E)
.It	  		RemoteVision MX (RV605)
.It	  		Sabrent TV-FM
.It	  		Sigma TVII-FM
.It	  		Spirit TV Tuner
.It	  		STB Gateway P/N 6000699
.It	  		Super TV Tuner
.It	  		Tekram M205 PRO
.It	  		Teppro TEV-560
.It 	  		Tibet Systems 'Progress DVR' CS16
.It	  		Trust 814PCI
.It	  		Typhoon TV-Tuner PCI (50684)
.It	  		Typhoon TView RDS + FM Stereo 
.It	  		Typhoon TView TV/FM Tuner
.It	  		V-Gear MyVCD
.It	  		Vobis TV-Boostar
.El
.Pp
.Sh SEE ALSO
.Xr au0828 4 ,
.Xr benq 4 ,
.Xr  conex 4 ,
.Xr  cpiax 4 ,
.Xr  cx23885 4 ,
.Xr  cx88 4 ,
.Xr  em28xx 4 ,
.Xr  et61x251 4 ,
.Xr  finepix 4 ,
.Xr  gl860 4 ,
.Xr  hdpvr 4 ,
.Xr  ibmcam 4 ,
.Xr  ivtv 4 ,
.Xr  jeilinj 4 ,
.Xr  m5602 4 ,
.Xr  mars 4 ,
.Xr  meye 4 ,
.Xr  mr97310a 4 ,
.Xr  ov519 4 ,
.Xr ov534 4 ,
.Xr pacxxx 4 ,
.Xr pvrusb2 4 ,
.Xr pwc 4 ,
.Xr saa7134 4 ,
.Xr saa7164 4 ,
.Xr se401 4 ,
.Xr si470x 4 ,
.Xr sn9c102 4 ,
.Xr sn9c20x 4 ,
.Xr sonixj 4 ,
.Xr spca5xx 4 ,
.Xr sq905c 4 ,
.Xr stk014 4 ,
.Xr stv06xx 4 ,
.Xr sunplus 4 ,
.Xr t613 4 ,
.Xr tv8532 4 ,
.Xr usbvision 4 ,
.Xr uvc 4 ,
.Xr vc032x 4 ,
.Xr w9966 4 ,
.Xr w996x 4 ,
.Xr zc0301 4 ,
.Xr zc3xx 4 ,
.Xr zoran 4 ,
.Xr zr364xx 4 ,
.Xr webcamd 8
.Sh AUTHORS
.An -nosplit
The original
.Nm
driver was written by 
.An Gerd Knorr kraxel@bytesex.org
for the Linux TV project. It was ported to the FreeBSD webcamd port by 
.An Hans Petter Selasky hselasky@freebsd.org .
This man page was written by 
.An Dru Lavigne dru@freebsd.org .
.Pp
