.\"
.\" Copyright (c) 2010 Dru Lavigne <dru@freebsd.org>
.\"
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL 
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"
.Dd Nov 27, 2010
.Dt CX88 4
.Os FreeBSD
.Sh NAME
.Nm cx88
.Nd cx88 webcamd driver for PCI TV cards
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
The
.Nm
driver supports PCI TV cards based on Conexant's CX88 chipset.
.Pp
Devices using the
.Nm
driver become available to other applications once
.Xr webcamd 8
is loaded.
.Sh HARDWARE
The
.Nm
driver should work with the following TV cards. The
.Xr pciconfig 8
command can be used to determine the VendorID:ProductID of the device.
.Pp
.Bl -column -compact ".Li 0fe9:d62" "DViCO FusionHDTV USB"
.It Em "VendorID:ProductID" Ta Em Device
.It 0070:1400	 Ta "Hauppauge WinTV-HVR3000"  
.It 0070:1401	 Ta "Hauppauge WinTV-HVR3000"  
.It 0070:1402	 Ta "Hauppauge WinTV-HVR3000"  
.It 0070:1404	 Ta "Hauppauge WinTV-HVR3000"  
.It 0070:2801	 Ta "Hauppauge WinTV 28xxx (Roslyn)"               
.It 0070:3401	 Ta "Hauppauge WinTV 34xxx models"                        
.It 0070:6900	 Ta "Hauppauge WinTV-HVR4000"           
.It 0070:6902	 Ta "Hauppauge WinTV-HVR4000"           
.It 0070:6904	 Ta "Hauppauge WinTV-HVR4000"           
.It 0070:6905	 Ta "Hauppauge WinTV-HVR4000(Lite)"              
.It 0070:6906	 Ta "Hauppauge WinTV-HVR4000(Lite)"              
.It 0070:9000	 Ta "Hauppauge Nova-T DVB-T" 
.It 0070:9001	 Ta "Hauppauge Nova-T DVB-T" 
.It 0070:9002	 Ta "Hauppauge Nova-T DVB-T"                              
.It 0070:9200	 Ta "Hauppauge Nova-SE2 DVB-S"                            
.It 0070:9201	 Ta "Hauppauge Nova-S-Plus DVB-S"                         
.It 0070:9202	 Ta "Hauppauge Nova-S-Plus DVB-S"                         
.It 0070:9290	 Ta "Hauppauge WinTV-IR Only"                             
.It 0070:9400	 Ta "Hauppauge WinTV-HVR1100"                
.It 0070:9402	 Ta "Hauppauge WinTV-HVR1100"                
.It 0070:9600	 Ta "Hauppauge WinTV-HVR1300 MPEG Encoder"   
.It 0070:9601	 Ta "Hauppauge WinTV-HVR1300 MPEG Encoder"   
.It 0070:9602	 Ta "Hauppauge WinTV-HVR1300 MPEG Encoder"   
.It 0070:9800	 Ta "Hauppauge WinTV-HVR1100 DVB-T/Hybrid"  
.It 0070:9802	 Ta "Hauppauge WinTV-HVR1100 DVB-T/Hybrid"  
.It 1002:00f8	 Ta "ATI TV Wonder Pro"                                   
.It 1002:00f9	 Ta "ATI TV Wonder Pro"                                   
.It 1002:a101	 Ta "ATI HDTV Wonder"                                     
.It 1043:4823	 Ta "ASUS PVR-416"                                        
.It 107d:6611	 Ta "Leadtek Winfast 2000XP Expert"                       
.It 107d:6613	 Ta "Leadtek Winfast 2000XP Expert"                       
.It 107d:6618	 Ta "Leadtek TV2000 XP Global"                            
.It 107d:6620	 Ta "Leadtek Winfast DV2000"                              
.It 107d:6621	 Ta "Leadtek Winfast DV2000"                              
.It 107d:6630	 Ta "Leadtek PVR 2000"
.It 107d:6631	 Ta "Leadtek PVR 2000"
.It 107d:6632	 Ta "Leadtek PVR 2000"
.It 107d:6637	 Ta "Leadtek PVR 2000"
.It 107d:6638	 Ta "Leadtek PVR 2000"
.It 107d:663b	 Ta "Leadtek PVR 2000"                                    
.It 107d:663c	 Ta "Leadtek PVR 2000"
.It 107d:663d	 Ta "Leadtek PVR 2000"
.It 107d:6654	 Ta "Leadtek WinFast DTV1800 Hybrid"                      
.It 107d:665e	 Ta "WinFast DTV2000 H"                                   
.It 107d:665f	 Ta "WinFast DTV1000-T"                                   
.It 107d:6f18	 Ta "Leadtek TV2000 XP Global"                            
.It 107d:6f2b	 Ta "WinFast DTV2000 H rev. J"                            
.It 10fc:d003	 Ta "IODATA GV-VCP3/PCI"                                  
.It 10fc:d035	 Ta "IODATA GV/BCTV7E"                                    
.It 11bd:0051	 Ta "Pinnacle PCTV HD 800i"                               
.It 12ab:1788	 Ta "Pinnacle Hybrid PCTV"                                
.It 12ab:2300	 Ta "KWorld/VStream XPert DVB-T"             
.It 1421:0305	 Ta "KWorld HardwareMpegTV XPert"                         
.It 1421:0334	 Ta "ADS Tech Instant TV DVB-T PCI"                       
.It 1421:0341	 Ta "KWorld DVB-S 100"                                    
.It 1421:0390	 Ta "ADS Tech Instant Video PCI"                          
.It 1461:000a	 Ta "AverMedia AVerTV 303 (M126)"                                   
.It 1461:000b	 Ta "AverMedia AverTV Studio 303 (M126)"                            
.It 1461:8011	 Ta "AverMedia UltraTV Media Center"              
.It 1461:c111	 Ta "ASUS PVR-416"                                        
.It 1462:8606	 Ta "MSI TV-@nywhere Master"                              
.It 14c7:0106	 Ta "GDI Black Gold"                                      
.It 14c7:0107	 Ta "GDI Black Gold"                                      
.It 14f1:0084	 Ta "Geniatech DVB-S"                                     
.It 14f1:0187	 Ta "Conexant DVB-T reference design"                     
.It 14f1:0342	 Ta "Digital-Logic MICROSPACE" 
.It 14f1:0842	 Ta "NPG Tech Real TV FM Top 10"                          
.It 14f1:8852	 Ta "Geniatech X8000-MT DVBT"                             
.It 14f1:ea3d	 Ta "PowerColor RA330"                                    
.It 153b:1166	 Ta "TerraTec Cinergy 1400 DVB-T"                         
.It 153b:1177	 Ta "Terratec Cinergy HT PCI MKII"                        
.It 1540:2580	 Ta "Provideo PV259"                                      
.It 1554:4811	 Ta "PixelView"                                           
.It 1554:4813	 Ta "PixelView PlayTV P7000"                              
.It 1554:4935	 Ta "Prolink Pixelview MPEG 8000GT"                       
.It 1554:4976	 Ta "Prolink Pixelview Global Extreme"                    
.It 17de:0840	 Ta "KWorld HardwareMpegTV XPert"                         
.It 17de:0841	 Ta "Kworld MCE 200 Deluxe"                               
.It 17de:08a1	 Ta "KWorld/VStream XPert DVB-T"             
.It 17de:08a6	 Ta "KWorld/VStream XPert DVB-T"                          
.It 17de:08b2	 Ta "KWorld DVB-S 100"                                    
.It 17de:08c1	 Ta "Kworld PlusTV HD PCI 120 (ATSC 120)"                 
.It 17de:a8a6	 Ta "digitalnow DNTV Live! DVB-T"                         
.It 1822:0019	 Ta "digitalnow DNTV Live! DVB-T Pro"                     
.It 1822:0025	 Ta "digitalnow DNTV Live! DVB-T Pro"                     
.It 18ac:d500	 Ta "DViCO FusionHDTV 5"                        
.It 18ac:d530	 Ta "DViCO FusionHDTV 5 PCI nano"                         
.It 18ac:d610	 Ta "DViCO FusionHDTV 7 Gold"                             
.It 18ac:d800	 Ta "DViCO FusionHDTV 3 Gold-Q"  
.It 18ac:d810	 Ta "DViCO FusionHDTV 3 Gold-Q"                           
.It 18ac:d820	 Ta "DViCO FusionHDTV 3 Gold-T"                           
.It 18ac:db00	 Ta "DViCO FusionHDTV DVB-T1"                             
.It 18ac:db10	 Ta "DViCO FusionHDTV DVB-T Plus"                         
.It 18ac:db11	 Ta "DViCO FusionHDTV DVB-T Plus"                         
.It 18ac:db30	 Ta "DViCO FusionHDTV DVB-T PRO"                          
.It 18ac:db40	 Ta "DViCO FusionHDTV DVB-T Hybrid"                       
.It 18ac:db44	 Ta "DViCO FusionHDTV DVB-T Hybrid"                       
.It 18ac:db50	 Ta "DViCO FusionHDTV DVB-T Dual Digital"                 
.It 18ac:db54	 Ta "DViCO FusionHDTV DVB-T Dual Digital"                 
.It 18ac:dc00	 Ta "Samsung SMT 7020 DVB-S"                              
.It 18ac:dccd	 Ta "Samsung SMT 7020 DVB-S"                              
.It 7063:3000	 Ta "pcHDTV HD3000 HDTV"                                  
.It 7063:5500	 Ta "pcHDTV HD5500 HDTV"                                  
.It 8910:8888	 Ta "TBS 8910 DVB-S"                                      
.It 8920:8888	 Ta "TBS 8920 DVB-S/S2"                                   
.It a044:2011	 Ta "Omicom SS4 DVB-S/S2 PCI"                             
.It b022:3022	 Ta "Prof 6200 DVB-S"                                     
.It B033:3033	 Ta "PROF 7300 DVB-S/S2"                                  
.It b034:3034	 Ta "Prof 7301 DVB-S/S2"                                  
.It b200:4200	 Ta "SATTRADE ST4200 DVB-S/S2"                            
.It c180:c980	 Ta "Shenzhen TE-DTV-250"  
.It d460:9022	 Ta "TeVii S460 DVB-S/S2"                                 
.It		 	Ta "KWorld LTV883RF"
.It 		Ta "Kworld V-Stream Xpert DVD"
.It 		Ta "MSI TV-@nywhere"
.It 		Ta "Norwood Micro TV Tuner"
.It 		Ta "PixelView PlayTV Ultra Pro"
.It 		Ta "Prolink PlayTV PVR"

.El
.Pp
.Sh SEE ALSO
.Xr  au0828 4 ,
.Xr  benq 4 ,
.Xr  bttv 4 ,
.Xr  conex 4 ,
.Xr  cpiax 4 ,
.Xr  cx23885 4 ,
.Xr  em28xx 4 ,
.Xr  et61x251 4 ,
.Xr  finepix 4 ,
.Xr  gl860 4 ,
.Xr  hdpvr
.Xr  ibmcam 4 ,
.Xr  ivtv 4 ,
.Xr  jeilinj 4 ,
.Xr  m5602 4 ,
.Xr  mars 4 ,
.Xr  meye 4 ,
.Xr  mr97310a 4 ,
.Xr ov519 4 ,
.Xr ov534 4 ,
.Xr pacxxx 4 ,
.Xr pvrusb2 4 ,
.Xr pwc 4 ,
.Xr saa7134 4 ,
.Xr saa7164 4 ,
.Xr se401 4 ,
.Xr si470x 4 ,
.Xr sn9c102 4 ,
.Xr sn9c20x 4 ,
.Xr sonixj 4 ,
.Xr spca5xx 4 ,
.Xr sq905c 4 ,
.Xr stk014 4 ,
.Xr stv06xx 4 ,
.Xr sunplus 4 ,
.Xr t613 4 ,
.Xr tv8532 4 ,
.Xr usbvision 4 ,
.Xr uvc 4 ,
.Xr vc032x 4 ,
.Xr w9966 4 ,
.Xr w996x 4 ,
.Xr zc0301 4 ,
.Xr zc3xx 4 ,
.Xr zoran 4 ,
.Xr zr364xx 4 ,
.Xr webcamd 8
.Sh AUTHORS
.An -nosplit
The original
.Nm
driver was written by 
.An Gerd Knorr kraxel@bytesex.org
for the Linux TV project. It was ported to the FreeBSD webcamd port by 
.An Hans Petter Selasky hselasky@freebsd.org .
This man page was written by 
.An Dru Lavigne dru@freebsd.org .
.Pp
