.\"
.\" Copyright (c) 2010 Dru Lavigne <dru@freebsd.org>
.\"
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL 
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"
.Dd Dec 2, 2010
.Dt SAA7134 4
.Os FreeBSD
.Sh NAME
.Nm saa7134
.Nd webcamd driver for Philips SAA7134 TV cards
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
The
.Nm
driver supports TV cards based on the Philips SAA7134 chipset. 
.Pp
Devices using the
.Nm
driver become available to other applications once
.Xr webcamd 8
is loaded.
.Sh HARDWARE
The
.Nm
driver should work with the following TV cards. The
.Xr pciconfig 8
command can be used to determine the VendorID:ProductID of the device.
.Pp
.Bl -column -compact ".Li 0fe9:d62" "DViCO FusionHDTV USB"
.It Em "VendorID:ProductID" Ta Em Device
.It 0000:4016	 Ta "Beholder BeholdTV 401"                    
.It 0000:4036	 Ta "Beholder BeholdTV 403"                    
.It 0000:4037	 Ta "Beholder BeholdTV 403 FM"                 
.It 0000:4050	 Ta "Beholder BeholdTV 405"                    
.It 0000:4051	 Ta "Beholder BeholdTV 405 FM"                 
.It 0000:4070	 Ta "Beholder BeholdTV 407"                    
.It 0000:4071	 Ta "Beholder BeholdTV 407 FM"                 
.It 0000:4090	 Ta "Beholder BeholdTV 409"                    
.It 0000:4091	 Ta "Beholder BeholdTV 409 FM"                 
.It 0000:5051	 Ta "Beholder BeholdTV 505 RDS"                
.It 0000:505b	 Ta "Beholder BeholdTV 505 RDS"                
.It 0000:5071	 Ta "Beholder BeholdTV 507 RDS"                
.It 0000:507b	 Ta "Beholder BeholdTV 507 RDS"                
.It 0000:5201	 Ta "Beholder BeholdTV Columbus TVFM"          
.It 0070:6700	 Ta "Hauppauge WinTV-HVR1110 DVB-T/Hybrid"     
.It 0070:6701	 Ta "Hauppauge WinTV-HVR1110 DVB-T/Hybrid"     
.It 0070:6702	 Ta "Hauppauge WinTV-HVR1110 DVB-T/Hybrid"     
.It 0070:6703	 Ta "Hauppauge WinTV-HVR1110 DVB-T/Hybrid"     
.It 0070:6704	 Ta "Hauppauge WinTV-HVR1110 DVB-T/Hybrid"     
.It 0070:6705	 Ta "Hauppauge WinTV-HVR1110 DVB-T/Hybrid"     
.It 0070:6706	 Ta "Hauppauge WinTV-HVR1150 ATSC/QAM-Hybrid"  
.It 0070:6707	 Ta "Hauppauge WinTV-HVR1120 DVB-T/Hybrid"     
.It 0070:6708	 Ta "Hauppauge WinTV-HVR1150 ATSC/QAM-Hybrid"  
.It 0070:6709	 Ta "Hauppauge WinTV-HVR1120 DVB-T/Hybrid"     
.It 0070:670a	 Ta "Hauppauge WinTV-HVR1120 DVB-T/Hybrid"     
.It 0331:1421	 Ta "ADS Instant TV Duo Cardbus PTV331"        
.It 0919:2003	 Ta "Proteus Pro 2309"                         
.It 0919:2003	 Ta "Sabrent PCMCIA TV-PCB05"                  
.It 1019:4cb4	 Ta "Elitegroup ECS TVP3XP FM1216 PAL-BG,FM"  
.It 1019:4cb5	 Ta "Elitegroup ECS TVP3XP FM1236 NTSC,FM" 
.It 1019:4cb6	 Ta "Elitegroup ECS TVP3XP FM1246 PAL,FM" 
.It 102B:48d0	 Ta "Matrox CronosPlus"                        
.It 1043:0210	 Ta "ASUS Digimatrix TV"                       
.It 1043:4830	 Ta "ASUS TV-FM 7134"                          
.It 1043:4840	 Ta "ASUS TV-FM 7134"                          
.It 1043:4842	 Ta "ASUS TV-FM 7134"                          
.It 1043:4843	 Ta "ASUS TV-FM 7133"                          
.It 1043:4845	 Ta "ASUS TV-FM 7135"                          
.It 1043:4847	 Ta "Asus Europa Hybrid OEM"                   
.It 1043:4857	 Ta "Asus Tiger Rev:1.00"                      
.It 1043:4860	 Ta "Asus Europa2 OEM"                         
.It 1043:4862	 Ta "ASUSTeK P7131 Dual"                       
.It 1043:4871	 Ta "ASUS P7131 4871"                          
.It 1043:4876	 Ta "ASUSTeK P7131 Hybrid"                     
.It 1043:4878	 Ta "Asus Tiger 3in1"                          
.It 1048:226a	 Ta "ELSA EX-VISION 500TV"                     
.It 1048:226b	 Ta "ELSA EX-VISION 300TV"                     
.It 1048:226c	 Ta "ELSA EX-VISION 700TV"                     
.It 107d:6655	 Ta "Leadtek Winfast DTV1000S"                 
.It 1131:2001	 Ta "10MOONS PCI TV CAPTURE CARD"              
.It 1131:2001	 Ta "Proteus Pro"    
.It 1131:2004	 Ta "Philips EUROPA V3 reference design"       
.It 1131:2004	 Ta "Philips TOUGH DVB-T reference design"     
.It 1131:2004	 Ta "Zolid Hybrid TV Tuner PCI"                
.It 1131:2018	 Ta "Philips Tiger reference design"           
.It 1131:2304	 Ta "10MOONS TM300 TV Card"                    
.It 1131:230f	 Ta "Encore ENLTV-FM"                          
.It 1131:2341	 Ta "Encore ENLTV"                             
.It 1131:2342	 Ta "Encore ENLTV"                             
.It 1131:4e85	 Ta "SKNet Monster TV"                         
.It 1131:4ee9	 Ta "SKNet MonsterTV Mobile"                   
.It 1131:6752	 Ta "EMPRESS"                                  
.It 1131:7133	 Ta "AOPEN VA1000 POWER"                       
.It 1131:fe01	 Ta "KNC One TV-Station RDS" 
.It 11bd:002b	 Ta "Pinnacle PCTV Stereo"        
.It 11bd:002d	 Ta "Pinnacle PCTV 300i DVB-T + PAL"           
.It 11bd:002f	 Ta "Pinnacle PCTV 310i"                       
.It 12ab:0800	 Ta "UPMOST PURPLE TV"                         
.It 1421:0380	 Ta "ADS Tech Instant HDTV"                    
.It 1435:7330	 Ta "RTD Embedded Technologies VFG7330"        
.It 1435:7350	 Ta "RTD Embedded Technologies VFG7350"        
.It 1461:050c	 Ta "Nagase Sangyo TransGear 3000TV"           
.It 1461:1044	 Ta "AverMedia AVerTVHD MCE A180"              
.It 1461:10ff	 Ta "AverMedia DVD EZMaker"                    
.It 1461:2108	 Ta "AverMedia AverTV 305"                     
.It 1461:2115	 Ta "AverMedia AverTV Studio 305"              
.It 1461:2c00	 Ta "AverMedia TV Hybrid A16AR"                
.It 1461:2c05	 Ta "AverMedia AverTV DVB-T 777"                         
.It 1461:4155	 Ta "Avermedia M733A"                          
.It 1461:4255	 Ta "Avermedia M733A"                          
.It 1461:6360	 Ta "AverMedia A169 B1"                        
.It 1461:7360	 Ta "AverMedia A169 B"                         
.It 1461:9715	 Ta "Avermedia AVerTV Studio 307"              
.It 1461:9715	 Ta "Avermedia AVerTV Studio 507"              
.It 1461:a115	 Ta "AverMedia AverTV Studio 505"              
.It 1461:a11b	 Ta "Avermedia AVerTV Studio 507UA"            
.It 1461:a70a	 Ta "Avermedia AVerTV 307"                     
.It 1461:a70b	 Ta "AverMedia M156/Medion 2819"             
.It 1461:a7a1	 Ta "Avermedia DVB-S Pro A700"                 
.It 1461:a7a2	 Ta "Avermedia DVB-S Hybrid+FM A700"           
.It 1461:a836	 Ta "Avermedia M115"                           
.It 1461:b7e9	 Ta "AverMedia Cardbus TV/Radio (E501R)"       
.It 1461:d6ee	 Ta "AverMedia Cardbus TV/Radio (E500)"        
.It 1461:f01d	 Ta "Avermedia Super 007"                      
.It 1461:f11d	 Ta "Avermedia PCI pure analog (M135A)"        
.It 1461:f31d	 Ta "Avermedia AVerTV GO 007 FM Plus"          
.It 1461:f31e	 Ta "Avermedia M102"                           
.It 1461:f31f	 Ta "Avermedia AVerTV GO 007 FM"               
.It 1461:f436	 Ta "AverMedia Cardbus TV/Radio (E506R)"       
.It 1461:f636	 Ta "AverMedia MiniPCI DVB-T Hybrid M103"      
.It 1461:f736	 Ta "AverMedia MiniPCI DVB-T Hybrid M103"      
.It 1461:f936	 Ta "AverMedia Hybrid TV/Radio (A16D)"         
.It 1462:6231	 Ta "MSI TV@Anywhere plus"                     
.It 1462:8624	 Ta "MSI TV@Anywhere plus"                     
.It 1462:8625	 Ta "MSI TV@nywhere A/D v1.1"                  
.It 1489:0214	 Ta "LifeView FlyTV Platinum F/Gold"        
.It 1489:0301	 Ta "Genius VideoWonder DVB-T" 
.It 1489:0502	 Ta "LifeView/Typhoon/Genius FlyDVB-T Duo" 
.It 14c0:1212	 Ta "LifeView FlyTV Platinum Mini2"            
.It 153b:1142	 Ta "Terratec Cinergy 400 TV"                  
.It 153b:1143	 Ta "Terratec Cinergy 600 TV"                  
.It 153b:1152	 Ta "Terratec Cinergy 200 TV"                  
.It 153b:1158	 Ta "Terratec Cinergy 600 TV MK3"              
.It 153b:1160	 Ta "Terratec Cinergy 250 PCI TV"              
.It 153b:1162	 Ta "Terratec Cinergy 400 mobile"              
.It 153b:1172	 Ta "Terratec Cinergy HT PCMCIA"               
.It 153b:1175	 Ta "Terratec Cinergy HT PCI"                  
.It 1540:9524	 Ta "ProVideo PV952"                           
.It 16be:0003	 Ta "Medion 7134"                              
.It 16be:0005	 Ta "Medion 7134 Bridge #2"                    
.It 16be:0007	 Ta "Medion Md8800 Quadro"                     
.It 16be:0008	 Ta "Medion Md8800 Quadro"                     
.It 16be:000d	 Ta "Medion Md8800 Quadro"                     
.It 16be:5000	 Ta "Medion 7134"                              
.It 17de:7128	 Ta "Kworld Plus TV Analog Lite PCI"           
.It 17de:7201	 Ta "Tevion/KWorld DVB-T 220RF"                
.It 17de:7250	 Ta "KWorld DVB-T 210"                         
.It 17de:7350	 Ta "Kworld ATSC110/115"                       
.It 17de:7352	 Ta "Kworld ATSC110/115"                       
.It 1822:0022	 Ta "Twinhan Hybrid DTV-DVB 3056 PCI"          
.It 185b:c100	 Ta "Compro VideoMate TV"            
.It 185b:c200	 Ta "Compro VideoMate Gold+ Pal"               
.It 185b:c900	 Ta "Compro Videomate DVB-T300"                
.It 185b:c900	 Ta "Compro VideoMate S350/S300"               
.It 185b:c900	 Ta "Compro VideoMate T750"                    
.It 185b:c901	 Ta "Compro Videomate DVB-T200"                
.It 1894:a006	 Ta "KNC One TV-Station DVR"                   
.It 1894:fe01	 Ta "Typhoon TV Tuner RDS" 
.It 19d1:0138	 Ta "RoverMedia TV Link Pro FM"                
.It 1a7f:2008	 Ta "Encore ENLTV-FM v5.3"                     
.It 3016:2344	 Ta "Encore ENLTV"                             
.It 4e42:0138	 Ta "LifeView FlyVIDEO3000"                    
.It 4e42:0212	 Ta "LifeView FlyTV Platinum Mini"             
.It 4e42:0300	 Ta "Acorp TV134DS" 
.It 4E42:0306	 Ta "MSI TV@nywhere Duo" 
.It 4e42:0502	 Ta "LifeView/Typhoon/Genius FlyDVB-T Duo" 
.It 4e42:3502	 Ta "LifeView FlyDVB-T Hybrid Cardbus/MSI TV @nywhere A/D NB" 
.It 5168:0138	 Ta "LifeView FlyVIDEO3000"                    
.It 5168:0138	 Ta "LifeView/Typhoon FlyVIDEO2000"            
.It 5168:0212	 Ta "LifeView FlyTV Platinum Mini"             
.It 5168:0214	 Ta "LifeView FlyTV Platinum FM/Gold"        
.It 5168:0300	 Ta "LifeView FlyDVB-S"      
.It 5168:0301	 Ta "LifeView FlyDVB-T" 
.It 5168:0304	 Ta "LifeView FlyTV Platinum FM/Gold"        
.It 5168:0306	 Ta "LifeView FlyDVB-T DUO" 
.It 5168:0319	 Ta "LifeView FlyDVB Trio"                     
.It 5168:0502	 Ta "LifeView/Typhoon/Genius FlyDVB-T Duo" 
.It 5168:3306	 Ta "LifeView FlyDVB-T Hybrid Cardbus/MSI TV @nywhere A/D NB" 
.It 5168:3307	 Ta "LifeView FlyDVB-T Hybrid Cardbus/MSI TV @nywhere A/D NB" 
.It 5168:3502	 Ta "LifeView FlyDVB-T Hybrid Cardbus/MSI TV @nywhere A/D NB" 
.It 5168:5214	 Ta "LifeView FlyTV Platinum FM / Gold"        
.It 5169:0138	 Ta "LifeView FlyVIDEO3000 (NTSC)"             
.It 5169:1502	 Ta "LifeView FlyTV Platinum Mini"             
.It 5456:7135	 Ta "GoTView 7135 PCI"                         
.It 5ace:5050	 Ta "Beholder BeholdTV 505 FM"                 
.It 5ace:5070	 Ta "Beholder BeholdTV 507 FM" 
.It 5ace:5090	 Ta "BeholdTV 509 FM" 
.It 5ace:6070	 Ta "Beholder BeholdTV 607 FM"                 
.It 5ace:6071	 Ta "Beholder BeholdTV 607 FM"                 
.It 5ace:6072	 Ta "Beholder BeholdTV 607 RDS"                
.It 5ace:6073	 Ta "Beholder BeholdTV 607 RDS"                
.It 5ace:6090	 Ta "Beholder BeholdTV 609 FM"                 
.It 5ace:6091	 Ta "Beholder BeholdTV 609 FM"                 
.It 5ace:6092	 Ta "Beholder BeholdTV 609 RDS"                
.It 5ace:6093	 Ta "Beholder BeholdTV 609 RDS"                
.It 5ace:6190	 Ta "Beholder BeholdTV M6"                     
.It 5ace:6191	 Ta "Beholder BeholdTV M63"                    
.It 5ace:6193	 Ta "Beholder BeholdTV M6 Extra"               
.It 5ace:6290	 Ta "Beholder BeholdTV H6"                     
.It 5ace:7090	 Ta "Beholder BeholdTV A7"                     
.It 5ace:7190	 Ta "Beholder BeholdTV H7"                    
.It 5ace:7595	 Ta "Beholder BeholdTV X7"                     
.It 			ASUSTeK P7131 Analog
.It 			AVACS SmartTV
.It 			BMK MPEX Tuner
.It 			Compro Videomate DVB-T200A
.It 			Compro VideoMate TV Gold+II
.It 			Empire PCI TV-Radio LE
.It 			Genius TVGO AM11MCE
.It 			Hawell HW-404M7
.It 			Items MuchTV Plus / IT-005
.It 			Kworld Xpert TV PVR7134
.It 			Kworld/KuroutoShikou SAA7130-TVPCI
.It 			Kworld/Tevion V-Stream Xpert TV PVR7134
.It 			Manli MuchTV M-TV001
.It 			Manli MuchTV M-TV002
.It 			Medion 5044
.It 			Noval Prime TV 7133
.It 			NXP Snake DVB-S reference design
.It 			Philips Tiger - S Reference design
.It 			Sedna/MuchTV PC TV Cardbus TV/Radio (ITO25 Rev:2B)
.It 			Tevion MD 9717
.It 			Typhoon TV+Radio 90031
.It 			V-Stream Studio TV Terminator
.It 			Zogis Real Angel 220
.It 			Zolid Xpert TV7134
.El
.Pp
.Sh SEE ALSO
.Xr au0828 4 ,
.Xr benq 4 ,
.Xr bttv 4 ,
.Xr  conex 4 ,
.Xr  cpiax 4 ,
.Xr  cx23885 4 ,
.Xr  cx88 4 ,
.Xr  em28xx 4 ,
.Xr  et61x251 4 ,
.Xr  finepix 4 ,
.Xr  gl860 4 ,
.Xr  ibmcam 4 ,
.Xr  ivtv 4 ,
.Xr  jeilinj 4 ,
.Xr  m5602 4 ,
.Xr  mars 4 ,
.Xr  meye 4 ,
.Xr  mr97310a 4 ,
.Xr  ov519 4 ,
.Xr ov534 4 ,
.Xr pacxxx 4 ,
.Xr pvrusb2 4 ,
.Xr pwc 4 ,
.Xr saa7164 4 ,
.Xr se401 4 ,
.Xr si470x 4 ,
.Xr sn9c102 4 ,
.Xr sn9c20x 4 ,
.Xr sonixj 4 ,
.Xr spca5xx 4 ,
.Xr sq905c 4 ,
.Xr stk014 4 ,
.Xr stv06xx 4 ,
.Xr sunplus 4 ,
.Xr t613 4 ,
.Xr tv8532 4 ,
.Xr usbvision 4 ,
.Xr uvc 4 ,
.Xr vc032x 4 ,
.Xr w9966 4 ,
.Xr w996x 4 ,
.Xr zc0301 4 ,
.Xr zc3xx 4 ,
.Xr zoran 4 ,
.Xr zr364xx 4 ,
.Xr webcamd 8
.Sh AUTHORS
.An -nosplit
The original
.Nm
driver was written by 
.An Gerd Knorr kraxel@bytesex.org
for the Linux TV project. It was ported to the FreeBSD webcamd port by 
.An Hans Petter Selasky hselasky@freebsd.org .
This man page was written by 
.An Dru Lavigne dru@freebsd.org .
.Pp
