.\"
.\" Copyright (c) 2010 Dru Lavigne <dru@freebsd.org>
.\"
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL 
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"
.Dd Dec 3, 2010
.Dt ZC3XX 4
.Os FreeBSD
.Sh NAME
.Nm zc3xx
.Nd zc3xx webcamd driver for USB cameras
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
The
.Nm
driver supports USB cameras based on the Z-Star ZC301, ZC302P, and Vimicro VC30X chipsets. This is the GSPCA version of the driver.
.Pp
Devices using the
.Nm
driver become available to other applications once
.Xr webcamd 8
is loaded.
.Sh HARDWARE
The
.Nm
driver should work with the following USB cameras. The
.Xr usbconfig 8
command can be used to determine the VendorID:ProductID of a plugged in USB device.
.Pp
.Bl -column -compact ".Li 0fe9:d62" "DViCO FusionHDTV USB"
.It Em "VendorID:ProductID" Ta Em Device
.It 041e:041e	 Ta "Creative WebCam Live!"
.It 041e:4017	 Ta "Creative Webcam Mobile PD1090"
.It 041e:401c	 Ta "Creative NX"
.It 041e:401e	 Ta "Creative Nx Pro"
.It 041e:401f	 Ta "Creative Webcam Notebook PD1171"
.It 041e:4022	 Ta "Creative Webcam NX Pro"
.It 041e:4029	 Ta "Creative WebCam Vista Pro"
.It 041e:4034	 Ta "Creative Instant P0620"
.It 041e:4035	 Ta "Creative Instant P0620D"
.It 041e:4036	 Ta "Creative Live!"
.It 041e:403a	 Ta "Creative Nx Pro 2"
.It 041e:4051	 Ta "Creative Live!Cam Notebook Pro VF0250"
.It 041e:4053	 Ta "Creative Live!Cam Video IM"
.It 0458:7007	 Ta "Genius VideoCam V2"
.It 0458:700c	 Ta "Genius VideoCam V3"
.It 0458:700f	 Ta "Genius VideoCam Web V2"
.It 0461:0a00	 Ta "MicroInnovation WebCam320"
.It 046d:089d	 Ta "Logitech QuickCam E2500"
.It 046d:08a0	 Ta "Logitech QC IM"
.It 046d:08a1	 Ta "Logitech QC IM 0x08A1 +sound"
.It 046d:08a2	 Ta "Labtec Webcam Pro"
.It 046d:08a3	 Ta "Logitech QC Chat"
.It 046d:08a6	 Ta "Logitech QCim"
.It 046d:08a7	 Ta "Logitech QuickCam Image"
.It 046d:08a9	 Ta "Logitech Notebook Deluxe"
.It 046d:08aa	 Ta "Labtec Webcam Notebook"
.It 046d:08ac	 Ta "Logitech QuickCam Cool"
.It 046d:08ad	 Ta "Logitech QCCommunicate STX"
.It 046d:08ae	 Ta "Logitech QuickCam for Notebooks"
.It 046d:08af	 Ta "Logitech QuickCam Cool"
.It 046d:08b9	 Ta "Logitech QuickCam Express"
.It 046d:08d7	 Ta "Logitech QCam STX"
.It 046d:08d8	 Ta "Logitech Notebook Deluxe"
.It 046d:08d9	 Ta "Logitech QuickCam IM/Connect"
.It 046d:08da	 Ta "Logitech QuickCam Messenger"
.It 046d:08dd	 Ta "Logitech QuickCam for Notebooks"
.It 0471:0325	 Ta "Philips SPC 200 NC"
.It 0471:0326	 Ta "Philips SPC 300 NC"
.It 0471:032d	 Ta "Philips SPC 210 NC"
.It 0471:032e	 Ta "Philips SPC 315 NC"
.It 055f:c005	 Ta "Mustek Wcam300A"
.It 055f:d003	 Ta "Mustek WCam300A"
.It 055f:d004	 Ta "Mustek WCam300 AN"
.It 0698:2003	 Ta "CTX M730V built in"
.It 0ac8:0301	 Ta ""
.It 0ac8:0302	 Ta "Z-star Vimicro zc0302"
.It 0ac8:301b	 Ta "Z-Star zc301b"
.It 0ac8:303b	 Ta "Vimicro 0x303b"
.It 0ac8:305b	 Ta "Z-star Vimicro zc0305b"
.It 0ac8:307b	 Ta "PC Camera (ZS0211)"
.It 10fd:0128	 Ta "Typhoon Webshot II USB 300k"
.It 10fd:804d	 Ta "Typhoon Webshot II" 
.It 10fd:8050	 Ta "Logitech QuickCam"
.El
.Pp
.Sh SEE ALSO
.Xr a800 4 ,
.Xr af9005 4 ,
.Xr af9015 4 ,
.Xr anysee 4 ,
.Xr au0828 4 ,
.Xr au6610 4 ,
.Xr b2c2 4 ,
.Xr benq 4 ,
.Xr ce6230 4 ,
.Xr cinergy 4 ,
.Xr conex 4 ,
.Xr cpiax 4 ,
.Xr dib0700 4 ,
.Xr digitv 4 ,
.Xr dt200u 4 ,
.Xr dtv5100 4 ,
.Xr dw2102 4 ,
.Xr ec168 4 ,
.Xr em28xx 4 ,
.Xr et61x251 4 ,
.Xr finepix 4 ,
.Xr friio 4 ,
.Xr gl860 4 ,
.Xr gl861 4 ,
.Xr gp8psk 4 ,
.Xr hdpvr 4 ,
.Xr ibmcam 4 ,
.Xr jeilinj 4 ,
.Xr m5602 4 ,
.Xr m920x 4 ,
.Xr mars 4 ,
.Xr mr97310a 4 ,
.Xr nova-t 4 ,
.Xr opera1 4 ,
.Xr ov519 4 ,
.Xr ov534 4 ,
.Xr pacxxx 4 ,
.Xr pvrusb2 4 ,
.Xr pwc 4 ,
.Xr se401 4 ,
.Xr si470x 4 ,
.Xr siano 4 ,
.Xr sn9c102 4 ,
.Xr sn9c20x 4 ,
.Xr sonixj 4 ,
.Xr spca5xx 4 ,
.Xr sq905c 4 ,
.Xr stk014 4 ,
.Xr stv06xx 4 ,
.Xr sunplus 4 ,
.Xr t613 4 ,
.Xr ttusb2 4 ,
.Xr tv8532 4 ,
.Xr umt 4 ,
.Xr usbvision 4 ,
.Xr uvc 4 ,
.Xr vc032x 4 ,
.Xr vp702x 4 ,
.Xr vp7045 4 ,
.Xr w9966 4 ,
.Xr zc3xx 4 ,
.Xr zr364xx 4 ,
.Xr webcamd 8 
.Sh AUTHORS
.An -nosplit
The original
.Nm
driver was written by 
.An Jean-Francois Moine http://moinejf.free.fr and
.An Serge A. Suchkov Serge.A.S@tochka.ru
for the Video4Linux project. It was ported to the FreeBSD webcamd port by 
.An Hans Petter Selasky hselasky@freebsd.org .
This man page was written by 
.An Dru Lavigne dru@freebsd.org .
.Pp
